ARG POSTGRES_VERSION=17
FROM postgres:${POSTGRES_VERSION}

# Install build dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    ca-certificates \
    git \
    postgresql-server-dev-$PG_MAJOR \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Clone, build, and install pgvector
RUN git clone https://github.com/pgvector/pgvector.git /tmp/pgvector \
    && cd /tmp/pgvector \
    && make \
    && make install \
    && rm -rf /tmp/pgvector

# RUN echo '🌱 Seed our database 🌱 '
COPY ./databases/seed.sql /docker-entrypoint-initdb.d/
