# Conftest/OPA security policies for OpenThrottle Terraform.
#
# These encode the issues surfaced in the infra audit so they fail CI if a
# regression reintroduces them:
#
#   1. Cloud SQL must enforce encrypted connections (no cleartext SSL mode).
#   2. Cloud SQL must not be openly reachable (no public IP with 0.0.0.0/0).
#   3. The Terraform state bucket must have object versioning enabled.
#   4. Storage buckets must enforce uniform bucket-level access.
#
# Rules 1-4 are GCP-shaped and cannot match hcloud resources. That asymmetry is
# a hazard, not a convenience: without counterparts, a Hetzner box with an open
# firewall would pass this gate simply because no rule mentions it. Rules 5-7
# close that:
#
#   5. An hcloud firewall must not expose SSH to the whole internet.
#   6. An hcloud firewall must not expose Postgres or Redis at all.
#   7. An hcloud server must not disable backups.
#
# LIMITATION worth knowing before trusting these: Conftest evaluates HCL
# statically, so it only sees LITERAL values. A rule written as
# `source_ips = var.ssh_allowed_cidrs` is invisible here, and rules generated by
# a `dynamic` block are invisible too — which is how modules/hcloud_server
# writes its own rules. So 5-7 guard against a hand-written resource with
# hardcoded values, and the module's own safety comes from its variable
# validation (`ssh_allowed_cidrs` rejects 0.0.0.0/0) instead. Belt and braces,
# not one mechanism twice.
#
# Conftest parses `.tf` files via the HCL2 parser into:
#   input.resource.<resource_type>.<resource_name> = { ...body... }
#
# Run against a Terraform root:
#   conftest test --policy infra/tests/policy infra/environments/staging
#
# Self-test the policies against the fixtures:
#   conftest verify --policy infra/tests/policy

package main

import rego.v1

# --- helpers ---------------------------------------------------------------

# Resource bodies for a given type, regardless of HCL nesting shape.
# Conftest may represent a resource block as an object (single instance) or as
# an array of objects (multiple instances); normalize both to a set of bodies.
resource_bodies(resource_type) := bodies if {
	blocks := object.get(input, ["resource", resource_type], {})
	bodies := {body |
		some name
		raw := blocks[name]
		body := normalize(raw)[_]
	}
}

# An instance may be an object or a single-element array; always yield bodies.
normalize(raw) := [raw] if {
	is_object(raw)
}

normalize(raw) := raw if {
	is_array(raw)
}

# settings/ip_configuration blocks can be objects or arrays; flatten to objects.
sub_blocks(body, key) := result if {
	raw := object.get(body, [key], [])
	is_array(raw)
	result := raw
}

sub_blocks(body, key) := [raw] if {
	raw := object.get(body, [key], {})
	is_object(raw)
	count(raw) > 0
}

# --- 1. Cloud SQL: encrypted connections only ------------------------------

deny contains msg if {
	some body in resource_bodies("google_sql_database_instance")
	some settings in sub_blocks(body, "settings")
	some ipcfg in sub_blocks(settings, "ip_configuration")
	ipcfg.ssl_mode == "ALLOW_UNENCRYPTED_AND_ENCRYPTED"
	msg := "google_sql_database_instance: ssl_mode ALLOW_UNENCRYPTED_AND_ENCRYPTED permits cleartext connections; use ENCRYPTED_ONLY or TRUSTED_CLIENT_CERTIFICATE_REQUIRED."
}

# --- 2. Cloud SQL: no open public exposure ---------------------------------

deny contains msg if {
	some body in resource_bodies("google_sql_database_instance")
	some settings in sub_blocks(body, "settings")
	some ipcfg in sub_blocks(settings, "ip_configuration")
	some authnet in sub_blocks(ipcfg, "authorized_networks")
	authnet.value == "0.0.0.0/0"
	msg := "google_sql_database_instance: authorized_networks must not include 0.0.0.0/0 (open to the internet)."
}

# --- 3. Terraform state bucket: versioning enabled -------------------------

deny contains msg if {
	some name
	bucket := input.resource.google_storage_bucket[name]
	body := normalize(bucket)[_]
	is_state_bucket(body)
	not versioning_enabled(body)
	msg := sprintf("google_storage_bucket %q is a Terraform state bucket and must enable object versioning to protect state history.", [name])
}

is_state_bucket(body) if {
	contains(object.get(body, ["name"], ""), "terraform-state")
}

versioning_enabled(body) if {
	some versioning in sub_blocks(body, "versioning")
	versioning.enabled == true
}

# --- 4. Storage buckets: uniform bucket-level access -----------------------

deny contains msg if {
	some name
	bucket := input.resource.google_storage_bucket[name]
	body := normalize(bucket)[_]
	object.get(body, ["uniform_bucket_level_access"], false) != true
	msg := sprintf("google_storage_bucket %q must set uniform_bucket_level_access = true.", [name])
}

# --- 5. hcloud firewall: SSH must not be open to the world -----------------
#
# The GCP counterpart of this risk is handled by the VPC's default rules, which
# gcp_compute_e2 openly relies on. Hetzner has NO default rules, so an SSH rule
# with a literal 0.0.0.0/0 here is genuinely open to the internet.

hcloud_firewall_rules(body) := rules if {
	rules := sub_blocks(body, "rule")
}

open_cidr(ip) if ip == "0.0.0.0/0"

open_cidr(ip) if ip == "::/0"

deny contains msg if {
	some name
	fw := input.resource.hcloud_firewall[name]
	body := normalize(fw)[_]
	some rule in hcloud_firewall_rules(body)
	object.get(rule, ["direction"], "") == "in"
	format_int(to_number(object.get(rule, ["port"], "0")), 10) == "22"
	some ip in object.get(rule, ["source_ips"], [])
	open_cidr(ip)
	msg := sprintf("hcloud_firewall %q exposes SSH (port 22) to %v. Hetzner has no default VPC rules to fall back on, so this is open to the internet; scope it to administrative ranges.", [name, ip])
}

# --- 6. hcloud firewall: databases must never be exposed -------------------
#
# The compose template publishes neither 5432 nor 6379, so a firewall rule for
# them cannot be serving a legitimate purpose — it can only be exposing a
# database that a stray `ports:` entry has published.

deny contains msg if {
	some name
	fw := input.resource.hcloud_firewall[name]
	body := normalize(fw)[_]
	some rule in hcloud_firewall_rules(body)
	object.get(rule, ["direction"], "") == "in"
	port := format_int(to_number(object.get(rule, ["port"], "0")), 10)
	database_port(port)
	msg := sprintf("hcloud_firewall %q opens database port %s. Postgres and Redis run as containers that publish no host ports; opening this can only expose a database.", [name, port])
}

database_port("5432")

database_port("6379")

# --- 7. hcloud server: backups must not be disabled ------------------------
#
# This box holds the Postgres data directory, so it is the Hetzner analogue of
# requiring versioning on the state bucket (rule 3): cheap protection against
# an irreversible mistake. Backups are also only one of the two required
# layers — see databases/backup-offsite.sh for the offsite dump.

deny contains msg if {
	some name
	srv := input.resource.hcloud_server[name]
	body := normalize(srv)[_]
	object.get(body, ["backups"], true) == false
	msg := sprintf("hcloud_server %q sets backups = false. This host holds the Postgres data directory; leave Hetzner backups on (~20%% of server cost) and pair them with an offsite logical dump.", [name])
}
