// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/mail": {
    params: {};
  };
  "/mail/inbox/:id": {
    params: {
      "id": string;
    };
  };
  "/mail/compose": {
    params: {};
  };
  "/mail/drafts": {
    params: {};
  };
  "/mail/search": {
    params: {};
  };
  "/mail/trash": {
    params: {};
  };
  "/mail/sent": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/faq": {
    params: {};
  };
  "/docs": {
    params: {};
  };
  "/docs/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/settings" | "/mail" | "/mail/inbox/:id" | "/mail/compose" | "/mail/drafts" | "/mail/search" | "/mail/trash" | "/mail/sent" | "/robots.txt" | "/faq" | "/docs" | "/docs/*";
  };
  "routes/settings._index.tsx": {
    id: "routes/settings._index";
    page: "/settings";
  };
  "routes/_layout.mail.tsx": {
    id: "routes/_layout.mail";
    page: "/mail" | "/mail/inbox/:id" | "/mail/compose" | "/mail/drafts" | "/mail/search" | "/mail/trash" | "/mail/sent";
  };
  "routes/_layout.mail.inbox.$id.tsx": {
    id: "routes/_layout.mail.inbox.$id";
    page: "/mail/inbox/:id";
  };
  "routes/_layout.mail.compose.tsx": {
    id: "routes/_layout.mail.compose";
    page: "/mail/compose";
  };
  "routes/_layout.mail._index.tsx": {
    id: "routes/_layout.mail._index";
    page: "/mail";
  };
  "routes/_layout.mail.drafts.tsx": {
    id: "routes/_layout.mail.drafts";
    page: "/mail/drafts";
  };
  "routes/_layout.mail.search.tsx": {
    id: "routes/_layout.mail.search";
    page: "/mail/search";
  };
  "routes/_layout.mail.trash.tsx": {
    id: "routes/_layout.mail.trash";
    page: "/mail/trash";
  };
  "routes/_layout.mail.sent.tsx": {
    id: "routes/_layout.mail.sent";
    page: "/mail/sent";
  };
  "routes/robots[.]txt.tsx": {
    id: "routes/robots[.]txt";
    page: "/robots.txt";
  };
  "routes/faq._index.tsx": {
    id: "routes/faq._index";
    page: "/faq";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/docs.tsx": {
    id: "routes/docs";
    page: "/docs" | "/docs/*";
  };
  "routes/docs._index.tsx": {
    id: "routes/docs._index";
    page: "/docs";
  };
  "routes/docs.$.tsx": {
    id: "routes/docs.$";
    page: "/docs/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/settings._index": typeof import("./app/routes/settings._index.tsx");
  "routes/_layout.mail": typeof import("./app/routes/_layout.mail.tsx");
  "routes/_layout.mail.inbox.$id": typeof import("./app/routes/_layout.mail.inbox.$id.tsx");
  "routes/_layout.mail.compose": typeof import("./app/routes/_layout.mail.compose.tsx");
  "routes/_layout.mail._index": typeof import("./app/routes/_layout.mail._index.tsx");
  "routes/_layout.mail.drafts": typeof import("./app/routes/_layout.mail.drafts.tsx");
  "routes/_layout.mail.search": typeof import("./app/routes/_layout.mail.search.tsx");
  "routes/_layout.mail.trash": typeof import("./app/routes/_layout.mail.trash.tsx");
  "routes/_layout.mail.sent": typeof import("./app/routes/_layout.mail.sent.tsx");
  "routes/robots[.]txt": typeof import("./app/routes/robots[.]txt.tsx");
  "routes/faq._index": typeof import("./app/routes/faq._index.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/docs": typeof import("./app/routes/docs.tsx");
  "routes/docs._index": typeof import("./app/routes/docs._index.tsx");
  "routes/docs.$": typeof import("./app/routes/docs.$.tsx");
};