fragment RoleDetails on RoleObject {
  createdAt
  description
  id
  name
  permissions {
    createdAt
    description
    id
    name
  }
  updatedAt
}

query getRole($id: ID!) {
  role(id: $id) {
    ...RoleDetails
  }
}

query getRolePermissions {
  permissions {
    description
    id
    name
  }
}

mutation updateRole($input: UpdateRoleInput!) {
  updateRole(input: $input) {
    ...RoleDetails
  }
}

mutation deleteRole($id: ID!) {
  deleteRole(id: $id)
}

mutation addPermissionToRole($input: AddPermissionToRoleInput!) {
  addPermissionToRole(input: $input)
}

mutation removePermissionFromRole($input: RemovePermissionFromRoleInput!) {
  removePermissionFromRole(input: $input)
}
