# OpenThrottle E2: server + developer + mcp + Caddy, plus a one-shot
# migrations runner and a manual bootstrap. Generated by Terraform.
#
# Postgres and Redis are absent ON PURPOSE — they are Cloud SQL and
# Memorystore on this path. Compare
# applications/openthrottle_hcloud/templates/docker-compose.yml.tpl, where
# they run as containers.
# Hardened for a shared-core e2-micro: per-service mem/cpu limits keep one
# container from OOM/CPU-starving the host (and taking Caddy down with it),
# plus cap_drop + read-only root filesystems to reduce blast radius.
services:
  caddy:
    cap_add:
      # Bind to privileged ports 80/443 without running as full root.
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    cpus: 0.25
    depends_on:
      # Wait for both apps to report healthy so Caddy never proxies to a
      # not-yet-ready upstream (avoids transient 502s on boot).
      openthrottle-developer:
        condition: service_healthy
      openthrottle-server:
        condition: service_healthy
    image: ${caddy_image}
    mem_limit: 128m
    ports:
      - "80:80"
      - "443:443"
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    volumes:
      # Read-only config; persistent volumes for issued certs and runtime state.
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_config:/config
      - caddy_data:/data

  openthrottle-developer:
    cap_drop:
      - ALL
    cpus: 0.5
    env_file: .env
    healthcheck:
      # curl is present on the production-debian image target (the distroless
      # default has neither shell nor curl); mirror the server healthcheck.
      # The React Router app serves SSR HTML at / on port 3000.
      interval: 30s
      retries: 3
      start_period: 40s
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      timeout: 10s
    image: ${developer_image}
    mem_limit: 384m
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    user: "1000:1000"

  openthrottle-server:
    cap_drop:
      - ALL
    cpus: 0.75
    depends_on:
      # The schema gate. Previously absent, which meant the server could start
      # against whatever schema Cloud SQL happened to have. A failed migration
      # now prevents the server from starting at all rather than letting it
      # serve a stale schema.
      migrations:
        condition: service_completed_successfully
    env_file: .env
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      timeout: 10s
    image: ${server_image}
    mem_limit: 512m
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    user: "1000:1000"

  #############################################################################
  #
  #     🗄️ migrations | one-shot: apply pending migrations, then exit
  #
  #     Mirrors the root docker-compose.yml. Idempotent, so running it on every
  #     deploy is safe and is what applies schema upgrades to Cloud SQL.
  #
  #     No POSTGRES_HOST override: .env already carries the Cloud SQL address
  #     that Terraform resolved.
  #
  migrations:
    cap_drop:
      - ALL
    cpus: 0.5
    env_file: .env
    image: ${migrations_image}
    mem_limit: 384m
    read_only: true
    restart: "no"
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp

  #############################################################################
  #
  #     🧠 mcp | openthrottle-mcp over streamable HTTP
  #
  #     No published host port: when mcp_domain is set Caddy reaches it over the
  #     compose network, and when it is not, mcp is unreachable from outside by
  #     construction. Auth is OPENTHROTTLE_MCP_AUTH_TOKEN, which the manual
  #     bootstrap step provisions.
  #
  mcp:
    cap_drop:
      - ALL
    cpus: 0.25
    depends_on:
      openthrottle-server:
        condition: service_healthy
    env_file: .env
    image: ${mcp_image}
    mem_limit: 256m
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp

  #############################################################################
  #
  #     🔐 bootstrap | one-shot MANUAL: default user + service-account creds
  #
  #     NEVER runs on `docker compose up` — it is profile-gated and no service
  #     depends on it, because `up` must never silently provision a database
  #     that may be shared. After the first successful `up`:
  #
  #         docker compose run --rm bootstrap
  #
  #     Idempotent. Until it has run there is no login user and no
  #     OPENTHROTTLE_MCP_AUTH_TOKEN, so mcp will not serve.
  #
  bootstrap:
    cap_drop:
      - ALL
    command: ["-r", "dotenv/config", "build/src/bootstrap.js"]
    depends_on:
      migrations:
        condition: service_completed_successfully
    env_file: .env
    image: ${server_image}
    mem_limit: 384m
    profiles: [bootstrap]
    read_only: true
    restart: "no"
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp

volumes:
  caddy_config:
  caddy_data:
