import * as React from 'react';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  Input,
  Label,
} from '@openthrottle/react-router-shadcn';
import { AgentsSkillsRegistryGrid } from '~/routing/agents/components/AgentsSkillsRegistryGrid';
import {
  getRepoSkillsRegistryCounts,
  type RepoSkillEntry,
} from '~/routing/agents/data/repo-skills-registry';
import { filterEntries } from '~/routing/agents/utils/filter-repo-skill-entries';

export interface AgentsSkillsRegistryProps {
  className?: string;
  entries?: ReadonlyArray<RepoSkillEntry>;
}

/**
 * @description Lists repo skills discovered under `.agents/skills` (the SSOT view)
 * with GitHub links and copy-friendly paths for debugging misaligned skill picks.
 */
export const AgentsSkillsRegistry = (
  props: AgentsSkillsRegistryProps,
): React.ReactElement => {
  const { className, entries = [] } = props;

  // Hooks
  const [filterQuery, setFilterQuery] = React.useState('');

  // Setup
  const filtered = React.useMemo(
    () => filterEntries(entries, filterQuery),
    [entries, filterQuery],
  );

  const layoutCounts = React.useMemo(
    () => getRepoSkillsRegistryCounts(entries),
    [entries],
  );

  // Handlers

  // Markup

  // Life Cycle

  // 🔌 Short Circuit

  return (
    <div className={className ? `space-y-6 ${className}` : 'space-y-6'}>
      <Card className="bg-transparent">
        <CardHeader>
          <CardTitle className="text-base">Skill paths vs repo</CardTitle>
          <CardDescription>
            This table lists the{' '}
            <span className="text-foreground font-medium">
              {layoutCounts.agents} skills under{' '}
              <code className="text-xs">.agents/skills</code>
            </span>{' '}
            — OpenThrottle&rsquo;s source-of-truth view combining authored{' '}
            <code className="text-xs">skills/</code> and lockfile-installed
            external skills. Match these against files on disk when debugging a
            missing or misrouted skill. Every skill lives at{' '}
            <code className="text-xs">
              .agents/skills/&lt;slug&gt;/SKILL.md
            </code>
            ; per-editor fan-out (e.g.{' '}
            <code className="text-xs">.claude/skills</code>) is generated by
            ot-skill-sync and mirrors this set.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-2 pt-0">
          <Label
            className="text-muted-foreground text-xs"
            htmlFor="skills-registry-filter"
          >
            Filter by slug, path, or summary
          </Label>
          <Input
            autoComplete="off"
            id="skills-registry-filter"
            onChange={(e) => setFilterQuery(e.target.value)}
            placeholder="e.g. nx-workspace or .agents/skills"
            type="search"
            value={filterQuery}
          />
        </CardContent>
      </Card>

      <section>
        <h2 className="mb-1 text-sm font-semibold tracking-tight">
          .agents/skills (OpenThrottle SSOT)
        </h2>
        <p className="text-muted-foreground mb-3 text-sm">
          Primary registry for automation tied to this monorepo—use when a model
          picks the wrong skill slug or path.
        </p>
        {filtered.length > 0 ? (
          <AgentsSkillsRegistryGrid entries={filtered} />
        ) : (
          <p className="text-muted-foreground text-sm">
            No matching entries in this section.
          </p>
        )}
      </section>
    </div>
  );
};
