# OpenThrottle E2: server + developer + Caddy. Generated by Terraform.
services:
  caddy:
    depends_on:
      - openthrottle-server
      - openthrottle-developer
    image: ${caddy_image}
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  openthrottle-developer:
    env_file: .env
    image: ${developer_image}
    restart: unless-stopped

  openthrottle-server:
    env_file: .env
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      timeout: 10s
    image: ${server_image}
    restart: unless-stopped
