# OpenThrottle E2: server + developer + Caddy. Generated by Terraform.
# Hardened for a shared-core e2-micro: per-service mem/cpu limits keep one
# container from OOM/CPU-starving the host (and taking Caddy down with it),
# plus cap_drop + read-only root filesystems to reduce blast radius.
services:
  caddy:
    cap_add:
      # Bind to privileged ports 80/443 without running as full root.
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    cpus: 0.25
    depends_on:
      - openthrottle-server
      - openthrottle-developer
    image: ${caddy_image}
    mem_limit: 128m
    ports:
      - "80:80"
      - "443:443"
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    volumes:
      # Read-only config; persistent volumes for issued certs and runtime state.
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_config:/config
      - caddy_data:/data

  openthrottle-developer:
    cap_drop:
      - ALL
    cpus: 0.5
    env_file: .env
    image: ${developer_image}
    mem_limit: 384m
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    user: "1000:1000"

  openthrottle-server:
    cap_drop:
      - ALL
    cpus: 0.75
    env_file: .env
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      timeout: 10s
    image: ${server_image}
    mem_limit: 512m
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    user: "1000:1000"

volumes:
  caddy_config:
  caddy_data:
