#!/bin/bash
# OpenThrottle E2 startup: install Docker, write env and compose, run containers.
# Generated by Terraform (infra/applications/openthrottle). Do not edit on the instance.
set -e

export DEBIAN_FRONTEND=noninteractive
apt-get -qq update
apt-get -qq install -y ca-certificates curl
install -d /usr/share/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
apt-get -qq update
apt-get -qq install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

# Google Cloud SDK for gcloud auth configure-docker (Artifact Registry).
if ! command -v gcloud >/dev/null 2>&1; then
  echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" > /etc/apt/sources.list.d/google-cloud-sdk.list
  curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
  apt-get -qq update
  apt-get -qq install -y google-cloud-sdk
fi

install -d -m 0755 /opt/openthrottle
cd /opt/openthrottle

# Env file for server and developer (Compose env_file).
cat > .env << 'ENVEOF'
POSTGRES_HOST=${postgres_host}
POSTGRES_PORT=${postgres_port}
POSTGRES_DB=${postgres_db}
POSTGRES_USER=${postgres_user}
POSTGRES_PASSWORD=${postgres_password}
REDIS_HOST=${redis_host}
REDIS_PORT=${redis_port}
APP_URL=https://${api_domain}
CORS_ORIGINS=https://${developer_domain}
API_URI=https://${api_domain}
API_URL=https://${api_domain}
PORT=3000
ENVEOF

# Caddy reverse-proxy config (api + developer hostnames).
cat > Caddyfile << 'CADDYEOF'
${caddyfile_content}
CADDYEOF

# Docker Compose (server + developer + Caddy).
cat > docker-compose.yml << 'COMPOSEEOF'
${compose_content}
COMPOSEEOF

# Configure Docker to use Artifact Registry (default GCE SA has roles/artifactregistry.reader).
gcloud auth configure-docker ${registry_domain} --quiet

docker compose pull
docker compose up -d
