/**
 * @description Repo-relative skill paths for OpenThrottle editor configuration.
 * Keep aligned with `applications/openthrottle-developer/app/routing/agents/data/repo-skills-registry.ts`.
 *
 * Skills live under `.agents/skills` — the SSOT view that combines authored
 * `skills/*` and lockfile-installed external skills. Per-editor fan-out is
 * generated by skill-sync and is not represented here; every editor reads
 * `.agents/skills`.
 */

interface RepoSkillPathEntry {
  readonly repoRelativePath: string;
  readonly slug: string;
}

/**
 * @description Skill paths used when applying editor configuration to linked repos.
 */
export const OPENTHROTTLE_REPO_SKILL_PATHS: readonly RepoSkillPathEntry[] = [
  {
    repoRelativePath: '.agents/skills/brag-sheet/SKILL.md',
    slug: 'brag-sheet',
  },
  {
    repoRelativePath: '.agents/skills/git-commit/SKILL.md',
    slug: 'git-commit',
  },
  {
    repoRelativePath: '.agents/skills/link-workspace-packages/SKILL.md',
    slug: 'link-workspace-packages',
  },
  {
    repoRelativePath: '.agents/skills/monitor-ci/SKILL.md',
    slug: 'monitor-ci',
  },
  {
    repoRelativePath: '.agents/skills/nx-workspace/SKILL.md',
    slug: 'nx-workspace',
  },
  {
    repoRelativePath: '.agents/skills/openthrottle-generators/SKILL.md',
    slug: 'openthrottle-generators',
  },
  {
    repoRelativePath: '.agents/skills/openthrottle-stack/SKILL.md',
    slug: 'openthrottle-stack',
  },
  {
    repoRelativePath: '.agents/skills/ot-claude-loop/SKILL.md',
    slug: 'ot-claude-loop',
  },
  {
    repoRelativePath: '.agents/skills/ot-plans/SKILL.md',
    slug: 'ot-plans',
  },
  {
    repoRelativePath: '.agents/skills/workflow-ralph/SKILL.md',
    slug: 'workflow-ralph',
  },
];
