/**
 * @description Per-worktree provisioning: skills sync, .env reset, app-port
 * remapping, docker-compose isolation, service-account token sync, install and
 * build. Invoked through the thin scripts/setup_worktree.sh shim, which
 * resolves tsx from the primary checkout because a fresh linked worktree has
 * no node_modules yet — which also means this script may import node builtins
 * and scripts/lib only (the shared logger degrades gracefully without chalk).
 *
 * Runs with cwd = the worktree root (the shim guarantees it).
 */
import { spawnSync } from 'node:child_process';
import { existsSync, globSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { run } from './lib/exec.ts';
import { createLogger } from './lib/logger.ts';
import { resetEnvironmentFiles } from './setup_environment.ts';
import { APP_PORT_NAMES, CANONICAL_APP_PORTS, resolveWorktreePorts } from './lib/worktree-ports.ts'; // prettier-ignore
import type { AppPortName } from './lib/worktree-ports.ts';

const logger = createLogger();

/**
 * Remap the canonical app ports (6020..6026) onto this worktree's block. The
 * 70xx targets never overlap the 60xx sources, so one pass is internally
 * consistent and idempotent (a re-run finds no 602x left). Exact word-boundary
 * matches leave Postgres/Redis (6010/6011) and comment numbers (6012,
 * 604800000) alone. Exported for tests.
 */
export const rewritePortsInContent = (
  contents: string,
  ports: Record<AppPortName, number>,
): string => {
  let result = contents;

  for (const app of APP_PORT_NAMES) {
    const canonical = CANONICAL_APP_PORTS[app];
    result = result.replace(new RegExp(`\\b${canonical}\\b`, 'g'), String(ports[app])); // prettier-ignore
  }

  return result;
};

/** First `KEY=value` match in raw .env contents (the shell's `sed | head -n1`). */
export const firstEnvMatch = (
  contents: string,
  key: string,
): string | undefined => {
  for (const line of contents.split('\n')) {
    if (line.startsWith(`${key}=`)) {
      return line.slice(key.length + 1);
    }
  }

  return undefined;
};

/** Replace the `KEY=...` line, or append one when the key is absent. */
export const upsertEnvLine = (
  contents: string,
  key: string,
  value: string,
): string => {
  const pattern = new RegExp(`^${key}=.*$`, 'm');

  if (pattern.test(contents)) {
    return contents.replace(pattern, `${key}=${value}`);
  }

  const separator = contents === '' || contents.endsWith('\n') ? '' : '\n';

  return `${contents}${separator}${key}=${value}\n`;
};

/** Placeholder tokens (ot_sa_xxx…) and empties must never be synced. */
export const isSyncableSecret = (value: string | undefined): value is string =>
  value !== undefined && value !== '' && !value.includes('xxxxxx');

const COMPOSE_OVERRIDE = `# Generated by scripts/setup_worktree.ts — DO NOT edit by hand.
#
# Worktrees share the main checkout's Postgres/Redis. This override disables the
# postgres/redis services and points the apps at the host DB. Bring up the apps
# with both files:
#   docker compose -f docker-compose.yml -f docker-compose.worktree.yml up
#   docker compose -f docker-compose.yml -f docker-compose.worktree.yml --profile dev up
services:
  postgres:
    profiles: ["disabled"]
  redis:
    profiles: ["disabled"]
  server:
    depends_on: !reset null
    environment:
      POSTGRES_HOST: host.docker.internal
      REDIS_HOST: host.docker.internal
  server-dev:
    depends_on: !reset null
    environment:
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: \${POSTGRES_PORT}
      REDIS_HOST: host.docker.internal
      REDIS_PORT: \${REDIS_PORT}
`;

/** Every .env this worktree owns: the root one plus each application's. */
const envFilePaths = (): string[] =>
  ['.env', ...globSync('applications/*/.env')].filter((path) =>
    existsSync(path),
  );

/**
 * Make `docker compose` worktree-safe: container names and the compose
 * project get a per-worktree prefix, and a generated override skips the
 * shared Postgres/Redis (the worktree's apps talk to the main checkout's DB
 * on the host instead of starting their own).
 */
const generateWorktreeCompose = (): void => {
  const slug = basename(process.cwd()).toLowerCase();

  // .env is reset from .env.default each setup, so appending never accumulates.
  const isolation = [
    '',
    '# --- worktree compose isolation (generated by setup_worktree.ts) ---',
    `COMPOSE_PROJECT_NAME=openthrottle-${slug}`,
    `OT_CONTAINER_PREFIX=wt-${slug}-`,
    '',
  ].join('\n');

  writeFileSync('.env', readFileSync('.env', 'utf8') + isolation);
  writeFileSync('docker-compose.worktree.yml', COMPOSE_OVERRIDE);
};

/**
 * setup_environment resets every .env back to .env.default, which ships
 * PLACEHOLDER service-account tokens. Carry the real tokens over from the
 * source checkout (a known-good session) into the worktree's .env files.
 */
const syncSecretsFromSource = (): void => {
  let source = process.env.OT_SOURCE_REPO ?? '';

  if (source === '') {
    // Standalone run: the main working tree is the parent of the common git dir.
    const commonDir = run('git', ['rev-parse', '--path-format=absolute', '--git-common-dir'], { allowFailure: true }); // prettier-ignore
    source = commonDir.exitCode === 0 ? dirname(commonDir.stdout) : '';
  }

  if (source === '' || !existsSync(source) || source === process.cwd()) {
    return;
  }

  let synced = false;

  for (const relative of ['.env', 'applications/openthrottle-server/.env']) {
    const from = `${source}/${relative}`;

    if (!existsSync(from) || !existsSync(relative)) {
      continue;
    }

    const fromContents = readFileSync(from, 'utf8');

    for (const key of [
      'OPENTHROTTLE_MCP_AUTH_TOKEN',
      'OPENTHROTTLE_WORKER_GRAPHQL_AUTH_TOKEN',
    ]) {
      // prettier-ignore
      const value = firstEnvMatch(fromContents, key);

      if (!isSyncableSecret(value)) {
        continue;
      }

      writeFileSync(relative, upsertEnvLine(readFileSync(relative, 'utf8'), key, value)); // prettier-ignore
      synced = true;
    }
  }

  if (synced) {
    logger.info('🔑 synced service-account token(s) from source checkout');
  }
};

/** Run a provisioning step streaming to the terminal; throw on failure. */
const step = (command: string, args: string[] = []): void => {
  const outcome = spawnSync(command, args, { stdio: 'inherit' });

  if (outcome.error) {
    throw new Error(`${command} failed to start: ${outcome.error.message}`);
  }

  if (outcome.status !== 0) {
    throw new Error(`${command} exited with code ${outcome.status ?? 1}`);
  }
};

const main = async (): Promise<void> => {
  // 0. Set up our skills (pre-install by design — owned by ot-skill-sync).
  step('./skills/ot-skill-sync/scripts/sync.sh');

  // 1. Create the environment file(s) — resets each .env to .env.default
  //    unconditionally: worktree provisioning always starts from the template
  //    (ports and tokens are layered back on below).
  await resetEnvironmentFiles(process.cwd(), async () => true);

  // 1b. Offset this worktree's app ports so concurrent worktrees don't fight
  //     the main checkout's dev servers. Postgres/Redis stay shared.
  //     create_worktree.ts passes OT_PORT_* in the environment; resolve here
  //     too so a standalone `setup_worktree.sh` run still gets a block.
  let base = Number(process.env.OT_PORT_BASE ?? '') || undefined;
  let ports =
    base === undefined
      ? undefined
      : {
          admin: Number(process.env.OT_PORT_ADMIN ?? base + 2),
          cms: Number(process.env.OT_PORT_CMS ?? base + 3),
          developer: Number(process.env.OT_PORT_DEVELOPER ?? base),
          email: Number(process.env.OT_PORT_EMAIL ?? base + 4),
          mcp: Number(process.env.OT_PORT_MCP ?? base + 6),
          server: Number(process.env.OT_PORT_SERVER ?? base + 1),
          website: Number(process.env.OT_PORT_WEBSITE ?? base + 5),
        };

  if (base === undefined) {
    try {
      const resolved = resolveWorktreePorts(basename(process.cwd()), {
        worktreeDir: process.cwd(),
      });
      base = resolved.base;
      ports = resolved.ports;
    } catch {
      // Port allocation is best-effort; the canonical block still works.
    }
  }

  if (base !== undefined && ports !== undefined && base !== 6020) {
    for (const path of envFilePaths()) {
      writeFileSync(path, rewritePortsInContent(readFileSync(path, 'utf8'), ports)); // prettier-ignore
    }

    generateWorktreeCompose();
    logger.info(`🔌 worktree app ports → block ${base}-${base + 6}`);
  }

  // 1c. Carry real service-account tokens over the placeholder reset.
  syncSecretsFromSource();

  // 2. Install the dependencies.
  step('pnpm', ['install']);

  // 3. Build our packages.
  step('pnpm', ['build']);

  // 4. Echo we're done.
  logger.info('🌳 worktree setup complete 🌳');
  logger.info(`   - path: ${process.cwd()}`);

  if (base !== undefined && ports !== undefined && base !== 6020) {
    logger.info(`   - developer: http://localhost:${ports.developer}`);
    logger.info(`   - server:    http://localhost:${ports.server}`);
    logger.info(`   - mcp (HTTP): http://localhost:${ports.mcp}/mcp  (docker: --profile prod up mcp)`); // prettier-ignore
  }

  logger.blank();
};

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await main();
}
