#!/usr/bin/env sh
set -e

# 0. Assume the basics if you're kicking off a worktree

# 0. Setup our skills
./skills/ot-skill-sync/scripts/sync.sh

# 1. Create the environment file(s) — resets each .env to .env.default (6020-6025).
./scripts/setup_environment.sh

# 1b. Offset this worktree's six app ports so concurrent worktrees don't fight
#     the main checkout's dev servers. Postgres/Redis stay shared (untouched).
#     create_worktree.sh exports OT_PORT_* before calling us; resolve here too
#     so a standalone `setup_worktree.sh` run still gets a block.
# shellcheck source=scripts/worktree_ports.sh
. ./scripts/worktree_ports.sh
if [ -z "${OT_PORT_BASE:-}" ]; then
  resolve_worktree_ports "$(basename "$PWD")" "$PWD" || true
fi

# Remap the canonical app ports (6020..6025) onto this worktree's block across
# every .env. The 70xx targets never overlap the 60xx sources, so one perl pass
# is internally consistent and idempotent (a re-run finds no 602x left). Exact
# \b matches leave Postgres/Redis (6010/6011) and comment numbers (6012,
# 604800000) alone.
rewrite_worktree_ports() {
  _prog="s/\\b6020\\b/${OT_PORT_DEVELOPER}/g;"
  _prog="${_prog}s/\\b6021\\b/${OT_PORT_SERVER}/g;"
  _prog="${_prog}s/\\b6022\\b/${OT_PORT_ADMIN}/g;"
  _prog="${_prog}s/\\b6023\\b/${OT_PORT_CMS}/g;"
  _prog="${_prog}s/\\b6024\\b/${OT_PORT_EMAIL}/g;"
  _prog="${_prog}s/\\b6025\\b/${OT_PORT_WEBSITE}/g;"
  _prog="${_prog}s/\\b6026\\b/${OT_PORT_MCP}/g;"
  for _f in .env applications/*/.env; do
    [ -f "$_f" ] || continue
    perl -i -pe "$_prog" "$_f"
  done
}

# Make `docker compose` worktree-safe too (the .env rewrite above already covers
# host `nx dev`). Container names and the compose project get a per-worktree
# prefix so they don't collide with the main checkout, and a generated override
# skips the shared Postgres/Redis — the worktree's apps talk to the main
# checkout's DB on the host instead of starting their own (which would fight for
# 6010/6011 and clobber its data).
generate_worktree_compose() {
  _slug=$(basename "$PWD" | tr '[:upper:]' '[:lower:]')

  # COMPOSE_PROJECT_NAME isolates networks/volumes/containers; OT_CONTAINER_PREFIX
  # feeds the parametrized container_name values in docker-compose.yml. .env is
  # reset from .env.default each setup, so appending fresh never accumulates.
  {
    printf '\n# --- worktree compose isolation (generated by setup_worktree.sh) ---\n'
    printf 'COMPOSE_PROJECT_NAME=openthrottle-%s\n' "$_slug"
    printf 'OT_CONTAINER_PREFIX=wt-%s-\n' "$_slug"
  } >>.env

  # Quoted heredoc: ${POSTGRES_PORT}/${REDIS_PORT} stay literal for compose to
  # interpolate from .env at runtime. !reset clears the depends_on so the apps
  # don't pull in the disabled Postgres/Redis services (needs Compose >= 2.24).
  cat >docker-compose.worktree.yml <<'YAML'
# Generated by scripts/setup_worktree.sh — DO NOT edit by hand.
#
# Worktrees share the main checkout's Postgres/Redis. This override disables the
# postgres/redis services and points the apps at the host DB. Bring up the apps
# with both files:
#   docker compose -f docker-compose.yml -f docker-compose.worktree.yml up
#   docker compose -f docker-compose.yml -f docker-compose.worktree.yml --profile dev up
services:
  postgres:
    profiles: ["disabled"]
  redis:
    profiles: ["disabled"]
  server:
    depends_on: !reset null
    environment:
      POSTGRES_HOST: host.docker.internal
      REDIS_HOST: host.docker.internal
  server-dev:
    depends_on: !reset null
    environment:
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: ${POSTGRES_PORT}
      REDIS_HOST: host.docker.internal
      REDIS_PORT: ${REDIS_PORT}
YAML
}

if [ -n "${OT_PORT_BASE:-}" ] && [ "$OT_PORT_BASE" != "6020" ]; then
  rewrite_worktree_ports
  generate_worktree_compose
  echo "🔌 worktree app ports → block ${OT_PORT_BASE}-$((OT_PORT_BASE + 6))"
fi

# 1c. setup_environment.sh reset every .env back to .env.default, which ships
#     PLACEHOLDER service-account tokens (ot_sa_xxx). The .mcp.json launcher does
#     `source ./.env` from the worktree root, so without the real token every
#     authed openthrottle-mcp call 401s. Carry the real tokens over from the
#     source checkout (a known-good session) into the worktree's .env files.
#     Values are passed to perl via the environment, never interpolated into a
#     logged command line.
sync_secrets_from_source() {
  _src=${OT_SOURCE_REPO:-}
  if [ -z "$_src" ]; then
    # Standalone run: the main working tree is the parent of the common git dir.
    _src=$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null) || _src=""
    [ -n "$_src" ] && _src=$(dirname "$_src")
  fi
  # Nothing to copy when there's no distinct source checkout.
  [ -n "$_src" ] && [ -d "$_src" ] && [ "$_src" != "$PWD" ] || return 0

  _synced=0
  for _rel in .env applications/openthrottle-server/.env; do
    _from="$_src/$_rel"
    [ -f "$_from" ] && [ -f "$_rel" ] || continue
    for _key in OPENTHROTTLE_MCP_AUTH_TOKEN OPENTHROTTLE_WORKER_GRAPHQL_AUTH_TOKEN; do
      _val=$(sed -n "s/^${_key}=//p" "$_from" | head -n1)
      # Skip empty and placeholder (ot_sa_xxx...) source values.
      case "$_val" in
        '' | *xxxxxx*) continue ;;
      esac
      if grep -qE "^${_key}=" "$_rel"; then
        OT_SYNC_KEY="$_key" OT_SYNC_VAL="$_val" \
          perl -i -pe 's/^\Q$ENV{OT_SYNC_KEY}\E=.*/$ENV{OT_SYNC_KEY}."=".$ENV{OT_SYNC_VAL}/e' "$_rel"
      else
        OT_SYNC_KEY="$_key" OT_SYNC_VAL="$_val" \
          sh -c 'printf "%s=%s\n" "$OT_SYNC_KEY" "$OT_SYNC_VAL"' >>"$_rel"
      fi
      _synced=1
    done
  done
  [ "$_synced" = "1" ] && echo "🔑 synced service-account token(s) from source checkout"
  return 0
}

sync_secrets_from_source

# 2. Install the dependencies
pnpm install

# 3. Build our packages
pnpm build

# 4. Echo we're done
echo "🌳 worktree setup complete 🌳"
echo "   - path: $PWD"
if [ -n "${OT_PORT_BASE:-}" ] && [ "$OT_PORT_BASE" != "6020" ]; then
  echo "   - developer: http://localhost:${OT_PORT_DEVELOPER}"
  echo "   - server:    http://localhost:${OT_PORT_SERVER}"
  echo "   - mcp (HTTP): http://localhost:${OT_PORT_MCP}/mcp  (docker: --profile prod up mcp)"
fi
echo ""
