import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const workspaceRoot = join(dirname(fileURLToPath(import.meta.url)), '..');

const rootSchemaPath = join(workspaceRoot, 'schema.gql');
const serverSchemaPath = join(
  workspaceRoot,
  'applications/openthrottle-server/schema.gql',
);

/**
 * @description Exits non-zero when repo-root schema.gql diverges from the server-generated copy.
 */
const main = (): void => {
  console.log(
    '🔍 Verifying root schema.gql matches openthrottle-server/schema.gql...\n',
  );

  let rootSchema: string;
  let serverSchema: string;

  try {
    rootSchema = readFileSync(rootSchemaPath, 'utf8');
    serverSchema = readFileSync(serverSchemaPath, 'utf8');
  } catch (error) {
    console.error('❌ Failed to read schema files:', error);
    process.exit(1);
  }

  if (rootSchema === serverSchema) {
    console.log('✅ Root and server GraphQL schemas are in sync.');
    process.exit(0);
  }

  console.error(
    '❌ GraphQL schema drift: schema.gql does not match applications/openthrottle-server/schema.gql.\n',
  );
  console.error(
    'The server schema is generated by NestJS (autoSchemaFile). After changing GraphQL types in openthrottle-server, copy the server file to the repo root:\n',
  );
  console.error(
    '  cp applications/openthrottle-server/schema.gql schema.gql\n',
  );
  console.error(
    'Then run consumer codegen (nx affected --target=codegen-graphql) and commit both files.\n',
  );

  process.exit(1);
};

main();
