# OpenThrottle on one Hetzner box: caddy + server + developer + mcp + postgres +
# redis + a one-shot migrations runner. Generated by Terraform
# (infra/applications/openthrottle_hcloud) — do not edit on the instance.
#
# Derived from applications/openthrottle/templates/docker-compose.yml.tpl, which
# renders only caddy + server + developer because on GCP Postgres and Redis are
# managed services. THAT FILE IS CORRECT FOR GCP and is deliberately unmodified;
# this is a sibling, not a replacement.
#
# Memory limits are re-tuned for a 4 GB CX22 rather than an e2-micro. They sum to
# 2400m, leaving ~1.2 GB for the page cache after the OS and Docker daemon — see
# infra/hetzner-topology.md for the arithmetic. Boot is not the peak: the
# migrations runner completes before server/developer/mcp are allowed to start.
#
# 🔒 5432 and 6379 are NEVER published on the host. Services reach each other
# over the compose network by service name. The firewall does not open them
# either, so this is defence in depth — but do not add a `ports:` entry here
# expecting the firewall to save you if the firewall is ever disabled.
#
# 🔀 The server reads POSTGRES_HOST / POSTGRES_PORT from .env, which Terraform
# renders from the postgres_host / postgres_port variables. The compose service
# name is NOT baked into any application config. That is what makes ladder rung 2
# (move Postgres off the box) a variable change instead of a rewrite.
services:
  caddy:
    cap_add:
      # Bind to privileged ports 80/443 without running as full root.
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    cpus: 0.25
    depends_on:
      # Wait for both apps to report healthy so Caddy never proxies to a
      # not-yet-ready upstream (avoids transient 502s on boot).
      #
      # mcp is deliberately NOT listed: coupling Caddy's start to it would mean a
      # broken mcp container takes the whole site down. Caddy retries instead,
      # so an mcp route 502s in isolation.
      openthrottle-developer:
        condition: service_healthy
      openthrottle-server:
        condition: service_healthy
    image: ${caddy_image}
    mem_limit: 128m
    ports:
      - "80:80"
      - "443:443"
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    volumes:
      # Read-only config; persistent volumes for issued certs and runtime state.
      # caddy_data MUST persist: it holds the ACME account key and issued
      # certificates, and losing it re-requests certificates on every restart,
      # which will hit Let's Encrypt rate limits.
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_config:/config
      - caddy_data:/data

  openthrottle-developer:
    cap_drop:
      - ALL
    cpus: 0.5
    depends_on:
      openthrottle-server:
        condition: service_healthy
    env_file: .env
    healthcheck:
      # curl is present on the production-debian image target (the distroless
      # default has neither shell nor curl); mirror the server healthcheck.
      # The React Router app serves SSR HTML at / on port 3000.
      interval: 30s
      retries: 3
      start_period: 40s
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      timeout: 10s
    image: ${developer_image}
    mem_limit: 448m
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    user: "1000:1000"

  openthrottle-server:
    cap_drop:
      - ALL
    cpus: 0.75
    depends_on:
      # service_completed_successfully is the schema gate: the server must never
      # start against a database whose pending migrations have not been applied.
      # A failed migrations run therefore prevents the server from starting at
      # all, rather than letting it serve against a stale schema.
      migrations:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: .env
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      timeout: 10s
    image: ${server_image}
    mem_limit: 640m
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    user: "1000:1000"

  #############################################################################
  #
  #     🧠 mcp | openthrottle-mcp over streamable HTTP
  #
  #     Absent from the GCP template — a known gap on that path, not a Hetzner
  #     addition (see infra/provider-contract.md). No published host port: when
  #     mcp_domain is set, Caddy reaches it over the compose network; when it is
  #     not, mcp is intentionally unreachable from outside the box.
  #
  #     Auth is OPENTHROTTLE_MCP_AUTH_TOKEN from .env, which
  #     `docker compose run --rm bootstrap` provisions. Until that manual step
  #     has run, this container fails loudly rather than serving unauthenticated.
  #
  mcp:
    cap_drop:
      - ALL
    cpus: 0.25
    depends_on:
      openthrottle-server:
        condition: service_healthy
    env_file: .env
    image: ${mcp_image}
    mem_limit: 256m
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp

  #############################################################################
  #
  #     🗄️ migrations | one-shot: apply pending migrations, then exit
  #
  #     Mirrors the root compose. Idempotent via the schema_migrations ledger, so
  #     re-running on every deploy is safe and is what applies schema upgrades.
  #
  #     No POSTGRES_HOST override here, unlike the root compose: .env already
  #     carries the correct value from Terraform. Overriding it to the literal
  #     `postgres` would break ladder rung 2 by pinning migrations to the on-box
  #     database while the server talked to a remote one.
  #
  migrations:
    cap_drop:
      - ALL
    cpus: 0.5
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    image: ${migrations_image}
    mem_limit: 384m
    read_only: true
    restart: "no"
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp

  #############################################################################
  #
  #     🐘 postgres | pgvector on PG18
  #
  #     Uses the upstream prebuilt pgvector image rather than
  #     applications/openthrottle/Dockerfile.Postgres: that Dockerfile COPYs
  #     databases/seed.sql, and a deployed box has no repository checkout to
  #     build from. The schema comes from the migrations runner instead, which is
  #     the correct source of truth for a deployment; seed.sql is a local-dev
  #     convenience.
  #
  postgres:
    cap_drop:
      - ALL
    cpus: 0.5
    env_file: .env
    healthcheck:
      interval: 10s
      retries: 10
      start_period: 30s
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      timeout: 5s
    image: ${postgres_image}
    mem_limit: 768m
    # ⚠️ read_only is deliberately NOT set. Postgres writes its data directory,
    # its Unix socket in /var/run/postgresql, and lock files — a read-only root
    # filesystem prevents it from starting. This is the one documented exception
    # to the hardening applied to every other service here; cap_drop,
    # no-new-privileges and the memory limit still apply.
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    # 🔒 No `ports:` — never publish 5432.
    shm_size: 128mb # required for pgvector
    volumes:
      # Bind mount to a host directory chosen by Terraform: either a path on the
      # attached block volume (data_volume_size_gb > 0) or one on the boot disk.
      # Keeping the decision in cloud-init means this template has one shape
      # regardless of which storage rung is in use.
      #
      # PG18 mounts /var/lib/postgresql, NOT /var/lib/postgresql/data — the
      # latter is the Postgres 17 path and mounting it on 18 silently produces an
      # empty cluster. Matches the root docker-compose.yml.
      - ${postgres_data_dir}:/var/lib/postgresql

  #############################################################################
  #
  #     🔴 redis | BullMQ queues and cache
  #
  #     read_only IS safe here despite Redis persisting: a volume mounted inside
  #     a read-only container is still writable, so /data works while the root
  #     filesystem stays immutable.
  #
  #     Persistence is kept on purpose. BullMQ jobs live in Redis, so running
  #     without a volume would silently drop queued work on every restart.
  #
  redis:
    cap_drop:
      - ALL
    command: redis-server
    cpus: 0.25
    healthcheck:
      interval: 10s
      retries: 3
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
    image: ${redis_image}
    mem_limit: 160m
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    # 🔒 No `ports:` — never publish 6379.
    volumes:
      - redis_data:/data

  #############################################################################
  #
  #     🔐 bootstrap | one-shot MANUAL: default user + service-account creds
  #
  #     NEVER runs on `docker compose up` — it is in its own profile and NO
  #     service depends on it, because `up` must never silently provision a
  #     possibly-shared database. After the first successful `up`:
  #
  #         docker compose run --rm bootstrap
  #
  #     Idempotent. Reuses the server image with the command overridden to the
  #     compiled bootstrap entrypoint. Until this has run there is no login user
  #     and no OPENTHROTTLE_MCP_AUTH_TOKEN, so the mcp container will not serve.
  #
  bootstrap:
    cap_drop:
      - ALL
    # ENTRYPOINT is node (distroless); override CMD to the bootstrap entry.
    command: ["-r", "dotenv/config", "build/src/bootstrap.js"]
    depends_on:
      migrations:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    env_file: .env
    image: ${server_image}
    mem_limit: 384m
    profiles: [bootstrap]
    read_only: true
    restart: "no"
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp

volumes:
  caddy_config:
  caddy_data: # ACME account key + issued certs; losing this re-requests certificates
  redis_data: # BullMQ job state
