#!/bin/bash
# OpenThrottle Hetzner cloud-init: install Docker, provision secrets, mount the
# data volume, write env/Caddyfile/compose, pull and start.
#
# Generated by Terraform (infra/applications/openthrottle_hcloud). Do not edit on
# the instance — user_data is in lifecycle.ignore_changes, so edits here do not
# reach a running box (see modules/hcloud_server/README.md).
#
# Adapted from applications/openthrottle/templates/startup.sh.tpl. That file is
# deliberately unmodified: the GCP path still needs its Google Cloud SDK block
# for `gcloud auth configure-docker`, and that path stays supported.
#
# What differs here:
#   - No Google Cloud SDK install at all. That block pulls the entire gcloud SDK
#     purely to authenticate Docker, and dropping it is most of this template's
#     first-boot speed and size win. GHCR needs at most a `docker login`.
#   - Ubuntu package setup (download.docker.com/linux/ubuntu, not /debian).
#   - Secrets are GENERATED HERE rather than interpolated (see SECRETS.md).
#   - The attached data volume is mounted before the stack starts.
#
# ⚠️ MUST BE IDEMPOTENT. Hetzner images are not dated/pinned the way GCP's are,
# and this script may re-run on a rebuild, so every step is written to be safe to
# repeat. In particular: it NEVER formats the data volume, and it never
# regenerates an existing secret.
set -euo pipefail

readonly APP_DIR=/opt/openthrottle
readonly SECRETS_FILE="$${APP_DIR}/.secrets"
readonly DATA_DIR="${postgres_data_dir}"
readonly VOLUME_DEVICE="${data_volume_device}"

log() { echo "[openthrottle-startup] $*"; }

################################################################################
# 1. Docker
################################################################################
export DEBIAN_FRONTEND=noninteractive

if ! command -v docker >/dev/null 2>&1; then
  log "installing docker"
  apt-get -qq update
  apt-get -qq install -y ca-certificates curl gnupg openssl
  install -m 0755 -d /usr/share/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg |
    gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  chmod a+r /usr/share/keyrings/docker-archive-keyring.gpg
  # shellcheck disable=SC1091  # /etc/os-release is provided by the OS
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$${VERSION_CODENAME}") stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get -qq update
  apt-get -qq install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
else
  log "docker already present"
  # openssl is needed below for secret generation even when docker is installed.
  command -v openssl >/dev/null 2>&1 || apt-get -qq install -y openssl
fi

install -d -m 0755 "$${APP_DIR}"
cd "$${APP_DIR}"

################################################################################
# 2. Data volume
#
# The volume is formatted ONCE by Hetzner at creation (hcloud_volume `format`),
# never here: user_data can re-run, and an mkfs would destroy the database.
#
# It is mounted by its stable /dev/disk/by-id path — kernel names like /dev/sdb
# are not stable across reboots.
#
# The wait matters: hcloud_volume_attachment is a SEPARATE resource applied after
# the server is created, so on a first apply this script can start running before
# the volume is attached. Without the wait, Postgres would initialize an empty
# cluster on the boot disk and the volume would sit unused.
################################################################################
if [[ -n "$${VOLUME_DEVICE}" ]]; then
  log "waiting for data volume $${VOLUME_DEVICE}"
  for _ in $(seq 1 60); do
    [[ -b "$${VOLUME_DEVICE}" ]] && break
    sleep 2
  done

  if [[ ! -b "$${VOLUME_DEVICE}" ]]; then
    log "FATAL: data volume $${VOLUME_DEVICE} never appeared after 120s"
    log "refusing to continue: starting Postgres now would silently initialize an empty"
    log "cluster on the boot disk while the real data volume stayed unmounted."
    exit 1
  fi

  # fstab entry so the mount survives reboots. nofail keeps a detached volume
  # from blocking boot entirely; discard lets the volume reclaim freed blocks.
  if ! grep -q "$${VOLUME_DEVICE}" /etc/fstab; then
    log "adding fstab entry for $${VOLUME_DEVICE}"
    echo "$${VOLUME_DEVICE} $(dirname "$${DATA_DIR}") ext4 discard,nofail,defaults 0 0" >> /etc/fstab
  fi

  install -d -m 0755 "$(dirname "$${DATA_DIR}")"
  mountpoint -q "$(dirname "$${DATA_DIR}")" || mount "$(dirname "$${DATA_DIR}")"
  log "data volume mounted at $(dirname "$${DATA_DIR}")"
else
  log "no data volume configured; Postgres data stays on the boot disk"
fi

# Postgres runs as uid 999 inside the container and the official entrypoint
# chowns its data directory on first init, so root ownership here is fine.
install -d -m 0700 "$${DATA_DIR}"

################################################################################
# 3. Secrets
#
# Generated on the box and persisted, so they never appear in user_data (which
# is readable via the Hetzner API) nor in Terraform state. See SECRETS.md.
#
# Generation is idempotent BY NECESSITY, not merely for tidiness: regenerating
# POSTGRES_PASSWORD would lock the server out of its own database, and
# regenerating JWT_SECRET would invalidate every issued session.
################################################################################
if [[ ! -f "$${SECRETS_FILE}" ]]; then
  log "generating secrets"
  umask 077

  # -hex gives 64 chars for 32 bytes, comfortably over the 32-BYTE minimum that
  # jwt.strategy.ts enforces for HS256.
  jwt_secret='${jwt_secret}'
  [[ -n "$${jwt_secret}" ]] || jwt_secret="$(openssl rand -hex 32)"

  postgres_password='${postgres_password}'
  [[ -n "$${postgres_password}" ]] || postgres_password="$(openssl rand -hex 24)"

  cat > "$${SECRETS_FILE}" << SECRETSEOF
JWT_SECRET=$${jwt_secret}
POSTGRES_PASSWORD=$${postgres_password}
SECRETSEOF
  chmod 0600 "$${SECRETS_FILE}"
else
  log "reusing existing secrets from $${SECRETS_FILE}"
fi

set +u
# shellcheck source=/dev/null  # generated at runtime; not available to analysis
. "$${SECRETS_FILE}"
set -u

################################################################################
# 4. .env for the compose stack
#
# JWT_SECRET is written under THAT EXACT NAME. .env.default defines only
# OPENTHROTTLE_DEVELOPER_JWT_SECRET and the root docker-compose.yml bridges the
# two; the compose file rendered here uses a plain `env_file: .env` with no such
# mapping, so writing only the prefixed name would leave the server throwing at
# boot.
#
# NODE_ENV=production is load-bearing beyond performance: isBullBoardEnabled()
# is `NODE_ENV !== "production"`, so this is what keeps the Bull Board dashboard
# — internet-reachable and guarded by a single static credential — switched off.
################################################################################
log "writing .env"
umask 077
# shellcheck disable=SC2153  # JWT_SECRET/POSTGRES_PASSWORD come from SECRETS_FILE
cat > "$${APP_DIR}/.env" << ENVEOF
APP_ENV=production
NODE_ENV=production
PORT=3000

POSTGRES_DB=${postgres_db}
POSTGRES_HOST=${postgres_host}
POSTGRES_PASSWORD=$${POSTGRES_PASSWORD}
POSTGRES_PORT=${postgres_port}
POSTGRES_USER=${postgres_user}

REDIS_HOST=${redis_host}
REDIS_PORT=${redis_port}

JWT_SECRET=$${JWT_SECRET}

API_URL=https://${api_domain}
API_URL_EXTERNAL=https://${api_domain}
API_URL_INTERNAL=http://openthrottle-server:3000
APP_URL=https://${api_domain}
APP_URL_DEVELOPER=https://${developer_domain}
CORS_ORIGINS=https://${developer_domain}

OT_MCP_HTTP_PORT=3000
ENVEOF
chmod 0600 "$${APP_DIR}/.env"
umask 022

################################################################################
# 5. Caddyfile + compose
################################################################################
log "writing Caddyfile"
cat > "$${APP_DIR}/Caddyfile" << 'CADDYEOF'
${caddyfile_content}
CADDYEOF

log "writing docker-compose.yml"
cat > "$${APP_DIR}/docker-compose.yml" << 'COMPOSEEOF'
${compose_content}
COMPOSEEOF

log "writing backup-offsite.sh"
cat > "$${APP_DIR}/backup-offsite.sh" << 'BACKUPSCRIPTEOF'
${backup_script}
BACKUPSCRIPTEOF
chmod 0755 "$${APP_DIR}/backup-offsite.sh"

################################################################################
# 6. Registry auth
#
# No gcloud SDK, and often no credential at all: GHCR packages for a public
# repository can be public, in which case anonymous pulls just work and NOTHING
# secret is in user_data. When they are private, this is the single unavoidable
# user_data secret — scope the token to read:packages only.
################################################################################
ghcr_username='${ghcr_username}'
ghcr_token='${ghcr_token}'

if [[ -n "$${ghcr_username}" && -n "$${ghcr_token}" ]]; then
  log "logging in to ghcr.io"
  printf '%s' "$${ghcr_token}" | docker login ghcr.io --username "$${ghcr_username}" --password-stdin
else
  log "no GHCR credentials supplied; relying on public packages"
fi
unset ghcr_token

################################################################################
# 7. Start
#
# `up -d` waits on the dependency conditions in the compose file, so the
# migrations runner must exit 0 before the server starts. A failed migration
# therefore prevents the server from serving a stale schema rather than being
# ignored.
################################################################################
log "pulling images"
docker compose pull --quiet

log "starting stack"
docker compose up -d --wait || {
  log "FATAL: stack did not come up healthy"
  docker compose ps
  log "migrations log follows (the usual culprit):"
  docker compose logs --no-color --tail=100 migrations || true
  exit 1
}

log "stack is up"

################################################################################
# 8. Nightly offsite backup
#
# On GCP, Cloud SQL handled this. Here it is owned work — and it is the real
# cost of the cheaper bill.
#
# This does NOT reuse the app's built-in scheduled backup. That job spawns
# `pnpm run database:backup` in a workspace checkout, and this box runs the
# server from a distroless image with no pnpm, no tsx and no workspace, so it
# cannot run here at all. Running at host level is also better for a backup: a
# broken or OOM-killed application must not stop backups, and that is precisely
# when they matter.
#
# Two independent layers protect this box. Hetzner server snapshots
# (backups_enabled) are layer one, but they share the server's fate for some
# failure modes. This is layer two: a logical dump on storage the box does not
# control. An on-box backup does not survive the failure mode it exists for.
#
# The dump runs INSIDE the postgres container: pg_dump refuses to dump a newer
# server, and PG18 client binaries exist nowhere else on this box.
################################################################################
backup_remote='${backup_remote}'

if [[ -n "$${backup_remote}" ]]; then
  log "installing nightly backup timer"

  install -d -m 0700 /var/backups/openthrottle

  # rclone is a single static binary and covers both realistic targets: a
  # Hetzner Storage Box (sftp) and any S3-compatible object storage.
  if ! command -v rclone >/dev/null 2>&1; then
    curl -fsSL https://rclone.org/install.sh | bash
  fi

  cat > /etc/systemd/system/openthrottle-backup.service << 'BACKUPSVCEOF'
[Unit]
Description=OpenThrottle nightly offsite database backup
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
WorkingDirectory=/opt/openthrottle
# Secrets come from the same root-only files the stack uses; nothing is baked
# into this unit, which is world-readable.
EnvironmentFile=/opt/openthrottle/.env
EnvironmentFile=/opt/openthrottle/.backup.env
ExecStart=/opt/openthrottle/backup-offsite.sh
BACKUPSVCEOF

  cat > /etc/systemd/system/openthrottle-backup.timer << 'BACKUPTIMEREOF'
[Unit]
Description=Run the OpenThrottle offsite backup nightly

[Timer]
OnCalendar=*-*-* 03:17:00
# Catch up after downtime rather than silently skipping a night.
Persistent=true
# Avoid every box in a fleet hitting object storage at the same instant.
RandomizedDelaySec=900

[Install]
WantedBy=timers.target
BACKUPTIMEREOF

  # Non-secret backup settings. OT_BACKUP_REMOTE is a destination, not a
  # credential; rclone's own config holds any credential.
  cat > /opt/openthrottle/.backup.env << BACKUPENVEOF
DATABASE_BACKUP_RETENTION_COUNT=${backup_retention_count}
OT_BACKUP_DIR=/var/backups/openthrottle
OT_BACKUP_PG_DUMP=docker compose -f /opt/openthrottle/docker-compose.yml exec -T -e PGPASSWORD postgres pg_dump
OT_BACKUP_REMOTE=${backup_remote}
BACKUPENVEOF
  chmod 0600 /opt/openthrottle/.backup.env

  systemctl daemon-reload
  systemctl enable --now openthrottle-backup.timer
  log "backup timer enabled (nightly 03:17 UTC, target $${backup_remote})"

  log "REMINDER: configure the rclone remote before the first run —"
  log "  rclone config   # then verify: rclone lsd $${backup_remote}"
  log "REMINDER: an untested backup is not a backup. Run a restore drill:"
  log "  databases/SEEDING.md and databases/verify-restore.sh"
else
  log "no backup remote configured; NO offsite backups will be taken"
  log "Hetzner snapshots alone share the server's fate for some failure modes."
fi

################################################################################
# 9. First-time provisioning — MANUAL, and deliberately never automatic
#
# `up` must NEVER silently provision a database: POSTGRES_HOST may point at a
# shared or pre-existing one (ladder rung 2), and seeding a default login user
# into someone else's database is not a recoverable mistake.
#
# So this script does NOT run it. After the first successful boot, SSH in and:
#
#     cd /opt/openthrottle
#     OPENTHROTTLE_MCP_AUTH_TOKEN='ot_sa_...' \
#     OPENTHROTTLE_BOOTSTRAP_USER_PASSWORD='...' \
#       docker compose run --rm bootstrap
#
# Idempotent, so it is safe to re-run — and safe to run before you have decided
# on every token, since bootstrap logs "Skip <account>: <VAR> not set" instead of
# failing. Passing the tokens in that one invocation's environment is how they
# reach the database WITHOUT ever entering user_data or Terraform state.
#
# Until it has run there is no login user and no MCP token, so the mcp container
# will not serve. That is expected, not a failure.
################################################################################
log "NEXT STEP (manual): docker compose run --rm bootstrap  # see SECRETS.md"
