fragment PlanCard on PlanObject {
  assignee
  author
  category
  createdAt
  description
  hasCustomRunConfig
  id
  project
  projectRelation {
    id
    name
  }
  status
  summary
  tags {
    dimension
    tag
  }
  taskCount
  tasksCompletedCount
  title
  updatedAt
}

query getPlanAssigneeOptions {
  listDistinctAuthorsAndAssignees
}

query getPlanCountsByStatus {
  planCountsByStatus {
    count
    status
  }
}

query getPlansByStatus($input: ListPlansByStatusInput!) {
  allPlansCount: listPlansByStatus(input: { statuses: [] }) {
    totalCount
  }

  # tasks: listPlanTasks(input: {
  #   planId: $id
  # }) {
  #   tasks {
  #     id
  #     name
  #     status
  #   }
  # }

  listPlansByStatus(input: $input) {
    plans {
      ...PlanCard
    }

    totalCount
  }

  queuedPlansCount: listPlansByStatus(input: { statuses: ["QUEUED"] }) {
    totalCount
  }
}
