fragment RolloutFlagFields on RolloutFlagObject {
  createdAt
  description
  enabled
  fallthrough {
    variations {
      variation
      weight
    }
  }
  id
  key
  kind
  offVariation
  targetRoles
  updatedAt
  variations {
    description
    name
    valueJson
  }
}

query listRolloutFlags {
  rolloutFlags {
    ...RolloutFlagFields
  }
}

mutation createRolloutFlag($input: CreateRolloutFlagInput!) {
  createRolloutFlag(input: $input) {
    ...RolloutFlagFields
  }
}

mutation deleteRolloutFlag($id: ID!) {
  deleteRolloutFlag(id: $id)
}
