name: '🚀 NX Release'
on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

concurrency:
  cancel-in-progress: true
  group: nx-release - ${{ github.ref }}

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name || 'main' }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GOOGLE_CREDENTIALS: ${{ (github.head_ref || github.ref_name || 'main') == 'main' && secrets.GOOGLE_CREDENTIALS_PRODUCTION || secrets.GOOGLE_CREDENTIALS_STAGING }}
  GOOGLE_PROJECT_ID: ${{ (github.head_ref || github.ref_name || 'main') == 'main' && vars.GOOGLE_PROJECT_ID_PRODUCTION || vars.GOOGLE_PROJECT_ID_STAGING }}
  NX_GCS_BUCKET: ${{ (github.head_ref || github.ref_name || 'main') == 'main' && 'openthrottle-staging-nx-cache' || 'openthrottle-staging-nx-cache' }}
  NX_KEY: ${{ vars.NX_KEY }}
  NX_VERSION: ${{ vars.NX_VERSION }} # https://github.com/visormatt/monorepo/settings/variables/actions
  RELEASE_DRY_RUN: ${{ (github.head_ref == 'main' || github.ref_name == 'main') && '--verbose' || '--dry-run --verbose' }}
  RELEASE_PUBLISH: ${{ (github.head_ref == 'main' || github.ref_name == 'main') && '--yes' || '--skip-publish' }}

permissions:
  contents: write
  # id-token: write # required for provenance data generation
  packages: write # required for publishing packages

jobs:
  release:
    # if: ${{ github.actor != 'dependabot[bot]' }}
    if: false # FIXME: 💰 Re-enable when we want to spend more
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: '📦 Checkout the code'
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0

      # Inject the dynamic bucket name directly into nx.json
      # Security: By using Strategy 2, you maintain the "Two-Bucket" security model which is the only way to protect your production cache from CREEP (CVE-2025-36852) when using bucket-based remote caching.
      - name: '🪣 NX Setup Cache'
        run: |
          sed -i 's/"bucket": ".*"/"bucket": "${{ env.NX_GCS_BUCKET }}"/' nx.json

      - name: '🌥️ Google Cloud Provider (GCP)'
        uses: ./.github/actions/google-cloud
        with:
          branch: ${{ env.BRANCH_NAME }}
          credentials_json: ${{ env.GOOGLE_CREDENTIALS }}
          google_cloud_project: ${{ env.GOOGLE_PROJECT_ID }}

      - name: '🤖 Node Setup'
        uses: ./.github/actions/node-setup

      - name: '🐙 Setup Git'
        run: |
          git config user.email "matthew.scholta@gmail.com"
          git config user.name "visormatt"

      - name: '🔍 Print Environment Info'
        run: pnpm dlx nx@${{ env.NX_VERSION }} report

      - name: '🚀 Release'
        run: pnpm dlx nx@${{ env.NX_VERSION }} release ${{ env.RELEASE_DRY_RUN }} ${{ env.RELEASE_PUBLISH }}
